version: '3.8'

services:
  api:
    build: SupportChat.API/
    restart: always
    volumes:
      - ./SupportChat.API:/app
    env_file:
      - ./config/.env
  proxy:
    image: nginx:latest
    volumes:
      - ./config/nginx_supportChat.conf:/etc/nginx/nginx.conf
    ports:
      - '80:5000'
      - '5022:5022'